# Generated by Django 3.2.4 on 2021-07-28 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_names', models.CharField(max_length=100)),
                ('guest_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('guest_no', models.CharField(blank=True, max_length=20, null=True, verbose_name='Guest Phone Number')),
                ('to_see', models.CharField(max_length=100)),
                ('time_in', models.DateTimeField(auto_now_add=True)),
                ('time_out', models.DateTimeField(auto_now=True)),
                ('signed_out', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
